/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import javax.swing.JOptionPane;
import sql.MetodesSQL;

/**
 *
 * @author garci
 */
public class AltaUsuari extends javax.swing.JFrame {

    /**
     * Creates new form DesktopPrincipal
     */
    public AltaUsuari() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
   MetodesSQL metodes = new MetodesSQL();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelUserIcon = new javax.swing.JLabel();
        jLabelUserConnected = new javax.swing.JLabel();
        jLabelTittle = new javax.swing.JLabel();
        jButtonLogout = new javax.swing.JButton();
        jLabelClose = new javax.swing.JLabel();
        jPanelCrearUsuaris = new javax.swing.JPanel();
        jLabelAltaTitulo = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jLabelContra = new javax.swing.JLabel();
        jPasswordFieldContra = new javax.swing.JPasswordField();
        jLabelNombre = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabelApe = new javax.swing.JLabel();
        jTextFieldApe = new javax.swing.JTextField();
        jLabelDep = new javax.swing.JLabel();
        jTextFieldDep = new javax.swing.JTextField();
        jButtonCrear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 600));

        jLabelUserIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_male_user_40px_1.png"))); // NOI18N

        jLabelUserConnected.setBackground(new java.awt.Color(51, 51, 51));
        jLabelUserConnected.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabelUserConnected.setForeground(new java.awt.Color(73, 181, 172));

        jLabelTittle.setBackground(new java.awt.Color(73, 181, 172));
        jLabelTittle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelTittle.setForeground(new java.awt.Color(73, 181, 172));
        jLabelTittle.setText("Desktop");

        jButtonLogout.setBackground(new java.awt.Color(73, 181, 172));
        jButtonLogout.setFont(new java.awt.Font("Segoe UI", 0, 21)); // NOI18N
        jButtonLogout.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLogout.setText("DESCONECTAR");
        jButtonLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });

        jLabelClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-close-24.png"))); // NOI18N
        jLabelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });

        jLabelAltaTitulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelAltaTitulo.setText("Alta Usuario");

        jLabelUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelUsuario.setText("Usuario:");

        jTextFieldUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabelContra.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelContra.setText("Contraseña:");

        jPasswordFieldContra.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabelNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelNombre.setText("Nombre:");

        jTextFieldNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabelApe.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelApe.setText("Apellido:");

        jTextFieldApe.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextFieldApe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldApeActionPerformed(evt);
            }
        });

        jLabelDep.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelDep.setText("Departamento:");

        jTextFieldDep.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jButtonCrear.setBackground(new java.awt.Color(73, 181, 172));
        jButtonCrear.setFont(new java.awt.Font("Segoe UI", 0, 21)); // NOI18N
        jButtonCrear.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCrear.setText("CREAR");
        jButtonCrear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCrearUsuarisLayout = new javax.swing.GroupLayout(jPanelCrearUsuaris);
        jPanelCrearUsuaris.setLayout(jPanelCrearUsuarisLayout);
        jPanelCrearUsuarisLayout.setHorizontalGroup(
            jPanelCrearUsuarisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCrearUsuarisLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabelAltaTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelCrearUsuarisLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanelCrearUsuarisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCrearUsuarisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabelApe)
                        .addComponent(jLabelNombre))
                    .addComponent(jLabelDep)
                    .addComponent(jLabelContra)
                    .addComponent(jLabelUsuario))
                .addGap(26, 26, 26)
                .addGroup(jPanelCrearUsuarisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldUsuario)
                    .addComponent(jPasswordFieldContra)
                    .addComponent(jTextFieldNombre)
                    .addComponent(jTextFieldApe)
                    .addComponent(jTextFieldDep, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE)
                .addComponent(jButtonCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        jPanelCrearUsuarisLayout.setVerticalGroup(
            jPanelCrearUsuarisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCrearUsuarisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCrearUsuarisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelCrearUsuarisLayout.createSequentialGroup()
                        .addComponent(jLabelAltaTitulo)
                        .addGap(51, 51, 51)
                        .addComponent(jLabelUsuario)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelContra)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelNombre)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelApe)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelDep))
                    .addGroup(jPanelCrearUsuarisLayout.createSequentialGroup()
                        .addGroup(jPanelCrearUsuarisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonCrear))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelCrearUsuarisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldDep, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCrearUsuarisLayout.createSequentialGroup()
                                .addComponent(jPasswordFieldContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addGroup(jPanelCrearUsuarisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanelCrearUsuarisLayout.createSequentialGroup()
                                        .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(43, 43, 43))
                                    .addComponent(jTextFieldApe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(43, 43, 43)))))
                .addContainerGap(114, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabelUserIcon)
                .addGap(18, 18, 18)
                .addComponent(jLabelUserConnected, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelClose)
                .addGap(14, 14, 14))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(410, 410, 410)
                        .addComponent(jButtonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(452, 452, 452)
                        .addComponent(jLabelTittle)))
                .addContainerGap(390, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addComponent(jPanelCrearUsuaris, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelClose)
                            .addComponent(jLabelUserIcon)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabelUserConnected, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(4, 4, 4)
                .addComponent(jLabelTittle)
                .addGap(25, 25, 25)
                .addComponent(jPanelCrearUsuaris, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jButtonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLogoutActionPerformed

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jTextFieldApeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldApeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldApeActionPerformed

    private void jButtonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearActionPerformed
     /*   int i = metodes.crearUser(jTextFieldUsuario.getText(), jPasswordFieldContra.getText(), jTextFieldNombre.getText(), jTextFieldApe.getText(), jTextFieldDep.getText());
        
        if (i > 0) {
            JOptionPane.showMessageDialog(this, "Usuario "+jTextFieldUsuario.getText()+" creado correctamente");
        } else {
            JOptionPane.showMessageDialog(this, "Usuario "+jTextFieldUsuario.getText()+" no se pudo crear correctamente");
        }*/
    }//GEN-LAST:event_jButtonCrearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AltaUsuari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AltaUsuari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AltaUsuari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AltaUsuari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AltaUsuari().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCrear;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JLabel jLabelAltaTitulo;
    private javax.swing.JLabel jLabelApe;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelContra;
    private javax.swing.JLabel jLabelDep;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelTittle;
    public javax.swing.JLabel jLabelUserConnected;
    private javax.swing.JLabel jLabelUserIcon;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelCrearUsuaris;
    private javax.swing.JPasswordField jPasswordFieldContra;
    private javax.swing.JTextField jTextFieldApe;
    private javax.swing.JTextField jTextFieldDep;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
