/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Utils.GestioUsuarisUtils;
import Utils.Usuaris;
import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import static java.lang.System.out;
import java.net.Socket;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Garcia_D
 */
public class DesktopAdmin extends javax.swing.JFrame {

    static int id;
    static String usuari;
    static int rol;

    public static int getRol() {
        return rol;
    }

    public static void setRol(int rol) {
        DesktopAdmin.rol = rol;
    }

    public static String getUsuari() {
        return usuari;
    }

    public static void setUsuari(String usuari) {
        DesktopAdmin.usuari = usuari;
    }
    static String pwd;

    public static String getPwd() {
        return pwd;
    }

    public static void setPwd(String pwd) {
        DesktopAdmin.pwd = pwd;
    }

    public static int getId() {
        return id;
    }

    public static void setId(int id) {
        DesktopAdmin.id = id;
    }

    /**
     * Creates new form DesktopPrincipal
     */
    public DesktopAdmin() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTop = new javax.swing.JPanel();
        jLabelTittle = new javax.swing.JLabel();
        jLabelUserIcon = new javax.swing.JLabel();
        jLabelUserConnected = new javax.swing.JLabel();
        jLabelMinimize = new javax.swing.JLabel();
        jLabelClose = new javax.swing.JLabel();
        jPanelMenuLeft = new javax.swing.JPanel();
        jPanelLogo = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelHomeMenu = new javax.swing.JLabel();
        jLabelTicketsMenu = new javax.swing.JLabel();
        jLabelStadisticsMenu = new javax.swing.JLabel();
        jLabelUserManagementMenu = new javax.swing.JLabel();
        jLabelDepManagementMenu = new javax.swing.JLabel();
        jLabelMessageMenu = new javax.swing.JLabel();
        jLabelDisconnect = new javax.swing.JLabel();
        jLabelSettingsMenu = new javax.swing.JLabel();
        jPaneMenuRight = new javax.swing.JPanel();
        jPanelHome = new javax.swing.JPanel();
        jLabelHome = new javax.swing.JLabel();
        jPanelTickets = new javax.swing.JPanel();
        jLabelTickets = new javax.swing.JLabel();
        jPanelStadistics = new javax.swing.JPanel();
        jLabelStadistics = new javax.swing.JLabel();
        jPanelUserManagement = new javax.swing.JPanel();
        jLabelUsers = new javax.swing.JLabel();
        jPanelUsers = new javax.swing.JPanel();
        jLabelNewUser = new javax.swing.JLabel();
        jLabelSearchUsers = new javax.swing.JLabel();
        jLabelModifyUsers = new javax.swing.JLabel();
        jLabelDelUsers = new javax.swing.JLabel();
        jComboBoxFiltraUsersRol = new javax.swing.JComboBox<>();
        jButtonRefreshListUsers1 = new javax.swing.JButton();
        jButtonRefreshListUsers = new javax.swing.JButton();
        jButtonDeleteUser = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableUsers = new javax.swing.JTable();
        jPanelUsersAdd = new javax.swing.JPanel();
        jLabelBack = new javax.swing.JLabel();
        jLabelAddUser = new javax.swing.JLabel();
        jLabelAddPwd = new javax.swing.JLabel();
        jLabelAddName = new javax.swing.JLabel();
        jLabelAddLastname = new javax.swing.JLabel();
        jLabelAddDepartment = new javax.swing.JLabel();
        jLabelAddRole = new javax.swing.JLabel();
        jLabelState = new javax.swing.JLabel();
        jTextFieldAddUser = new javax.swing.JTextField();
        jPasswordFieldAddPwd = new javax.swing.JPasswordField();
        jTextFieldAddName = new javax.swing.JTextField();
        jTextFieldAddLastname = new javax.swing.JTextField();
        jComboBoxAddDepartment = new javax.swing.JComboBox<>();
        jComboBoxAddRole = new javax.swing.JComboBox<>();
        jComboBoxAddState = new javax.swing.JComboBox<>();
        jLabelCleanAddPanel = new javax.swing.JLabel();
        jLabelUserAdd = new javax.swing.JLabel();
        jPanelDepManagement = new javax.swing.JPanel();
        jLabelDepManagement = new javax.swing.JLabel();
        jPanelMessage = new javax.swing.JPanel();
        jLabelMessage = new javax.swing.JLabel();
        jPanelSettings = new javax.swing.JPanel();
        jLabelSettings = new javax.swing.JLabel();
        jLabelTheme = new javax.swing.JLabel();
        jLabelLight = new javax.swing.JLabel();
        jLabelDark = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelTop.setBackground(new java.awt.Color(55, 55, 55));

        jLabelTittle.setBackground(new java.awt.Color(73, 181, 172));
        jLabelTittle.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabelTittle.setForeground(new java.awt.Color(73, 181, 172));
        jLabelTittle.setText("Dashboard");

        jLabelUserIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-male-user-24.png"))); // NOI18N

        jLabelUserConnected.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabelUserConnected.setForeground(new java.awt.Color(73, 181, 172));

        jLabelMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-subtract-24.png"))); // NOI18N
        jLabelMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinimizeMouseClicked(evt);
            }
        });

        jLabelClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-close-24.png"))); // NOI18N
        jLabelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelTopLayout = new javax.swing.GroupLayout(jPanelTop);
        jPanelTop.setLayout(jPanelTopLayout);
        jPanelTopLayout.setHorizontalGroup(
            jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTittle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 376, Short.MAX_VALUE)
                .addComponent(jLabelUserIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelUserConnected, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelMinimize)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelClose)
                .addContainerGap())
        );
        jPanelTopLayout.setVerticalGroup(
            jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTittle)
                    .addComponent(jLabelUserIcon)
                    .addComponent(jLabelClose)
                    .addComponent(jLabelUserConnected, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTopLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelMinimize)
                .addContainerGap())
        );

        getContentPane().add(jPanelTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 800, 40));

        jPanelMenuLeft.setBackground(new java.awt.Color(55, 55, 55));

        jPanelLogo.setBackground(new java.awt.Color(55, 55, 55));
        jPanelLogo.setPreferredSize(new java.awt.Dimension(200, 93));

        javax.swing.GroupLayout jPanelLogoLayout = new javax.swing.GroupLayout(jPanelLogo);
        jPanelLogo.setLayout(jPanelLogoLayout);
        jPanelLogoLayout.setHorizontalGroup(
            jPanelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelLogoLayout.setVerticalGroup(
            jPanelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 93, Short.MAX_VALUE)
        );

        jSeparator1.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));

        jLabelHomeMenu.setBackground(new java.awt.Color(51, 51, 51));
        jLabelHomeMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelHomeMenu.setForeground(new java.awt.Color(255, 255, 0));
        jLabelHomeMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/01 Inici Selected.png"))); // NOI18N
        jLabelHomeMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelHomeMenu.setOpaque(true);
        jLabelHomeMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelHomeMenuMouseClicked(evt);
            }
        });

        jLabelTicketsMenu.setBackground(new java.awt.Color(55, 55, 55));
        jLabelTicketsMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/02 Tiquets NoSelected.png"))); // NOI18N
        jLabelTicketsMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelTicketsMenu.setOpaque(true);
        jLabelTicketsMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelTicketsMenuMouseClicked(evt);
            }
        });

        jLabelStadisticsMenu.setBackground(new java.awt.Color(55, 55, 55));
        jLabelStadisticsMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/04 Estadistiques NoSelected.png"))); // NOI18N
        jLabelStadisticsMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelStadisticsMenu.setOpaque(true);
        jLabelStadisticsMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelStadisticsMenuMouseClicked(evt);
            }
        });

        jLabelUserManagementMenu.setBackground(new java.awt.Color(55, 55, 55));
        jLabelUserManagementMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/05 Gestio Usuaris NoSelected.png"))); // NOI18N
        jLabelUserManagementMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelUserManagementMenu.setOpaque(true);
        jLabelUserManagementMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelUserManagementMenuMouseClicked(evt);
            }
        });

        jLabelDepManagementMenu.setBackground(new java.awt.Color(55, 55, 55));
        jLabelDepManagementMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/08 Departaments NoSelected.png"))); // NOI18N
        jLabelDepManagementMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelDepManagementMenu.setOpaque(true);
        jLabelDepManagementMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDepManagementMenuMouseClicked(evt);
            }
        });

        jLabelMessageMenu.setBackground(new java.awt.Color(55, 55, 55));
        jLabelMessageMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/06 Missatges NoSelected.png"))); // NOI18N
        jLabelMessageMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMessageMenu.setOpaque(true);
        jLabelMessageMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMessageMenuMouseClicked(evt);
            }
        });

        jLabelDisconnect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-logout-40.png"))); // NOI18N
        jLabelDisconnect.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelDisconnect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDisconnectMouseClicked(evt);
            }
        });

        jLabelSettingsMenu.setBackground(new java.awt.Color(55, 55, 55));
        jLabelSettingsMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/07 Configuracio NoSelected.png"))); // NOI18N
        jLabelSettingsMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelSettingsMenu.setOpaque(true);
        jLabelSettingsMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSettingsMenuMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelMenuLeftLayout = new javax.swing.GroupLayout(jPanelMenuLeft);
        jPanelMenuLeft.setLayout(jPanelMenuLeftLayout);
        jPanelMenuLeftLayout.setHorizontalGroup(
            jPanelMenuLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelHomeMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelMenuLeftLayout.createSequentialGroup()
                .addGroup(jPanelMenuLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelDisconnect)
                    .addGroup(jPanelMenuLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelTicketsMenu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelStadisticsMenu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelUserManagementMenu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelMessageMenu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelLogo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelSettingsMenu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelDepManagementMenu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelMenuLeftLayout.setVerticalGroup(
            jPanelMenuLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLeftLayout.createSequentialGroup()
                .addComponent(jPanelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelHomeMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelTicketsMenu)
                .addGap(12, 12, 12)
                .addComponent(jLabelStadisticsMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelUserManagementMenu)
                .addGap(12, 12, 12)
                .addComponent(jLabelDepManagementMenu)
                .addGap(12, 12, 12)
                .addComponent(jLabelMessageMenu)
                .addGap(12, 12, 12)
                .addComponent(jLabelSettingsMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 169, Short.MAX_VALUE)
                .addComponent(jLabelDisconnect))
        );

        getContentPane().add(jPanelMenuLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 600));

        jPaneMenuRight.setBackground(new java.awt.Color(51, 51, 51));
        jPaneMenuRight.setPreferredSize(new java.awt.Dimension(1000, 600));
        jPaneMenuRight.setLayout(new java.awt.CardLayout());

        jPanelHome.setBackground(new java.awt.Color(51, 51, 51));

        jLabelHome.setBackground(new java.awt.Color(55, 55, 55));
        jLabelHome.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabelHome.setForeground(new java.awt.Color(204, 204, 204));
        jLabelHome.setText("Inici");

        javax.swing.GroupLayout jPanelHomeLayout = new javax.swing.GroupLayout(jPanelHome);
        jPanelHome.setLayout(jPanelHomeLayout);
        jPanelHomeLayout.setHorizontalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelHome)
                .addContainerGap(764, Short.MAX_VALUE))
        );
        jPanelHomeLayout.setVerticalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelHome)
                .addContainerGap(529, Short.MAX_VALUE))
        );

        jPaneMenuRight.add(jPanelHome, "card2");

        jPanelTickets.setBackground(new java.awt.Color(51, 51, 51));

        jLabelTickets.setBackground(new java.awt.Color(55, 55, 55));
        jLabelTickets.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabelTickets.setForeground(new java.awt.Color(204, 204, 204));
        jLabelTickets.setText("Tiquets");

        javax.swing.GroupLayout jPanelTicketsLayout = new javax.swing.GroupLayout(jPanelTickets);
        jPanelTickets.setLayout(jPanelTicketsLayout);
        jPanelTicketsLayout.setHorizontalGroup(
            jPanelTicketsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTicketsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTickets)
                .addContainerGap(740, Short.MAX_VALUE))
        );
        jPanelTicketsLayout.setVerticalGroup(
            jPanelTicketsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTicketsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTickets)
                .addContainerGap(529, Short.MAX_VALUE))
        );

        jPaneMenuRight.add(jPanelTickets, "card3");

        jPanelStadistics.setBackground(new java.awt.Color(51, 51, 51));

        jLabelStadistics.setBackground(new java.awt.Color(55, 55, 55));
        jLabelStadistics.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabelStadistics.setForeground(new java.awt.Color(204, 204, 204));
        jLabelStadistics.setText("Estadístiques");

        javax.swing.GroupLayout jPanelStadisticsLayout = new javax.swing.GroupLayout(jPanelStadistics);
        jPanelStadistics.setLayout(jPanelStadisticsLayout);
        jPanelStadisticsLayout.setHorizontalGroup(
            jPanelStadisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStadisticsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelStadistics)
                .addContainerGap(698, Short.MAX_VALUE))
        );
        jPanelStadisticsLayout.setVerticalGroup(
            jPanelStadisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStadisticsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelStadistics)
                .addContainerGap(529, Short.MAX_VALUE))
        );

        jPaneMenuRight.add(jPanelStadistics, "card5");

        jPanelUserManagement.setBackground(new java.awt.Color(51, 51, 51));
        jPanelUserManagement.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabelUsers.setBackground(new java.awt.Color(55, 55, 55));
        jLabelUsers.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabelUsers.setForeground(new java.awt.Color(204, 204, 204));
        jLabelUsers.setText("Gestió Usuaris");

        jPanelUsers.setBackground(new java.awt.Color(55, 55, 55));
        jPanelUsers.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanelUsers.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelNewUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-add-user-male-100.png"))); // NOI18N
        jLabelNewUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelNewUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelNewUserMouseClicked(evt);
            }
        });
        jPanelUsers.add(jLabelNewUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabelSearchUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-find-user-male-100.png"))); // NOI18N
        jLabelSearchUsers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelSearchUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSearchUsersMouseClicked(evt);
            }
        });
        jPanelUsers.add(jLabelSearchUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        jLabelModifyUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-registration-100.png"))); // NOI18N
        jLabelModifyUsers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelUsers.add(jLabelModifyUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        jLabelDelUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-delete-user-male-100.png"))); // NOI18N
        jLabelDelUsers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelDelUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDelUsersMouseClicked(evt);
            }
        });
        jPanelUsers.add(jLabelDelUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, -1, -1));

        jComboBoxFiltraUsersRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tots", "Administradors", "Tècnics", "Usuaris" }));
        jPanelUsers.add(jComboBoxFiltraUsersRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 120, 30));

        jButtonRefreshListUsers1.setBackground(new java.awt.Color(51, 51, 51));
        jButtonRefreshListUsers1.setForeground(new java.awt.Color(55, 55, 55));
        jButtonRefreshListUsers1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-filter-24.png"))); // NOI18N
        jButtonRefreshListUsers1.setBorderPainted(false);
        jButtonRefreshListUsers1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonRefreshListUsers1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshListUsers1ActionPerformed(evt);
            }
        });
        jPanelUsers.add(jButtonRefreshListUsers1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 80, 30, 30));

        jButtonRefreshListUsers.setBackground(new java.awt.Color(51, 51, 51));
        jButtonRefreshListUsers.setForeground(new java.awt.Color(55, 55, 55));
        jButtonRefreshListUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-update-left-rotation-24.png"))); // NOI18N
        jButtonRefreshListUsers.setBorderPainted(false);
        jButtonRefreshListUsers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonRefreshListUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshListUsersActionPerformed(evt);
            }
        });
        jPanelUsers.add(jButtonRefreshListUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 80, 30, 30));

        jButtonDeleteUser.setBackground(new java.awt.Color(51, 51, 51));
        jButtonDeleteUser.setForeground(new java.awt.Color(55, 55, 55));
        jButtonDeleteUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-trash-24.png"))); // NOI18N
        jButtonDeleteUser.setBorderPainted(false);
        jButtonDeleteUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonDeleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteUserActionPerformed(evt);
            }
        });
        jPanelUsers.add(jButtonDeleteUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 80, 30, 30));

        jTableUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableUsers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane1.setViewportView(jTableUsers);

        jPanelUsers.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 770, 390));

        jPanelUsersAdd.setBackground(new java.awt.Color(55, 55, 55));
        jPanelUsersAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanelUsersAdd.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-left-24.png"))); // NOI18N
        jLabelBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBackMouseClicked(evt);
            }
        });
        jPanelUsersAdd.add(jLabelBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabelAddUser.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabelAddUser.setForeground(new java.awt.Color(204, 204, 204));
        jLabelAddUser.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelAddUser.setText("Usuari");
        jLabelAddUser.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelAddUser.setFocusable(false);
        jPanelUsersAdd.add(jLabelAddUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 100, -1));

        jLabelAddPwd.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabelAddPwd.setForeground(new java.awt.Color(204, 204, 204));
        jLabelAddPwd.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelAddPwd.setText("Contrasenya");
        jLabelAddPwd.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelAddPwd.setFocusable(false);
        jPanelUsersAdd.add(jLabelAddPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 100, -1));

        jLabelAddName.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabelAddName.setForeground(new java.awt.Color(204, 204, 204));
        jLabelAddName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelAddName.setText("Nom");
        jLabelAddName.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelAddName.setFocusable(false);
        jPanelUsersAdd.add(jLabelAddName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 100, -1));

        jLabelAddLastname.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabelAddLastname.setForeground(new java.awt.Color(204, 204, 204));
        jLabelAddLastname.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelAddLastname.setText("Cognom");
        jLabelAddLastname.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelAddLastname.setFocusable(false);
        jPanelUsersAdd.add(jLabelAddLastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 100, -1));

        jLabelAddDepartment.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabelAddDepartment.setForeground(new java.awt.Color(204, 204, 204));
        jLabelAddDepartment.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelAddDepartment.setText("Departament");
        jLabelAddDepartment.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelAddDepartment.setFocusable(false);
        jPanelUsersAdd.add(jLabelAddDepartment, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 100, -1));

        jLabelAddRole.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabelAddRole.setForeground(new java.awt.Color(204, 204, 204));
        jLabelAddRole.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelAddRole.setText("Rol");
        jLabelAddRole.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelAddRole.setFocusable(false);
        jPanelUsersAdd.add(jLabelAddRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 100, -1));

        jLabelState.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabelState.setForeground(new java.awt.Color(204, 204, 204));
        jLabelState.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelState.setText("Estat");
        jLabelState.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelState.setFocusable(false);
        jPanelUsersAdd.add(jLabelState, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 100, -1));

        jTextFieldAddUser.setBackground(new java.awt.Color(51, 51, 51));
        jTextFieldAddUser.setForeground(new java.awt.Color(204, 204, 204));
        jTextFieldAddUser.setBorder(null);
        jTextFieldAddUser.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanelUsersAdd.add(jTextFieldAddUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 160, 25));

        jPasswordFieldAddPwd.setBackground(new java.awt.Color(51, 51, 51));
        jPasswordFieldAddPwd.setForeground(new java.awt.Color(204, 204, 204));
        jPasswordFieldAddPwd.setBorder(null);
        jPasswordFieldAddPwd.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanelUsersAdd.add(jPasswordFieldAddPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 160, 25));

        jTextFieldAddName.setBackground(new java.awt.Color(51, 51, 51));
        jTextFieldAddName.setForeground(new java.awt.Color(204, 204, 204));
        jTextFieldAddName.setBorder(null);
        jTextFieldAddName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanelUsersAdd.add(jTextFieldAddName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 160, 25));

        jTextFieldAddLastname.setBackground(new java.awt.Color(51, 51, 51));
        jTextFieldAddLastname.setForeground(new java.awt.Color(204, 204, 204));
        jTextFieldAddLastname.setBorder(null);
        jTextFieldAddLastname.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanelUsersAdd.add(jTextFieldAddLastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 160, 25));

        jComboBoxAddDepartment.setBackground(new java.awt.Color(51, 51, 51));
        jComboBoxAddDepartment.setForeground(new java.awt.Color(204, 204, 204));
        jComboBoxAddDepartment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        jComboBoxAddDepartment.setBorder(null);
        jComboBoxAddDepartment.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelUsersAdd.add(jComboBoxAddDepartment, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 90, 160, 25));

        jComboBoxAddRole.setBackground(new java.awt.Color(51, 51, 51));
        jComboBoxAddRole.setForeground(new java.awt.Color(204, 204, 204));
        jComboBoxAddRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jComboBoxAddRole.setBorder(null);
        jComboBoxAddRole.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelUsersAdd.add(jComboBoxAddRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, 160, 25));

        jComboBoxAddState.setBackground(new java.awt.Color(51, 51, 51));
        jComboBoxAddState.setForeground(new java.awt.Color(204, 204, 204));
        jComboBoxAddState.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1" }));
        jComboBoxAddState.setBorder(null);
        jComboBoxAddState.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelUsersAdd.add(jComboBoxAddState, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 170, 160, 25));

        jLabelCleanAddPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-broom-24.png"))); // NOI18N
        jLabelCleanAddPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelCleanAddPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCleanAddPanelMouseClicked(evt);
            }
        });
        jPanelUsersAdd.add(jLabelCleanAddPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 460, -1, -1));

        jLabelUserAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-add-user-male-24.png"))); // NOI18N
        jLabelUserAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelUserAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelUserAddMouseClicked(evt);
            }
        });
        jPanelUsersAdd.add(jLabelUserAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 460, -1, -1));

        javax.swing.GroupLayout jPanelUserManagementLayout = new javax.swing.GroupLayout(jPanelUserManagement);
        jPanelUserManagement.setLayout(jPanelUserManagementLayout);
        jPanelUserManagementLayout.setHorizontalGroup(
            jPanelUserManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUserManagementLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelUserManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelUserManagementLayout.createSequentialGroup()
                        .addComponent(jLabelUsers)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanelUsers, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanelUserManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelUserManagementLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanelUsersAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanelUserManagementLayout.setVerticalGroup(
            jPanelUserManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUserManagementLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelUsers)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanelUserManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelUserManagementLayout.createSequentialGroup()
                    .addContainerGap(37, Short.MAX_VALUE)
                    .addComponent(jPanelUsersAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        jPaneMenuRight.add(jPanelUserManagement, "card6");

        jPanelDepManagement.setBackground(new java.awt.Color(51, 51, 51));

        jLabelDepManagement.setBackground(new java.awt.Color(55, 55, 55));
        jLabelDepManagement.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabelDepManagement.setForeground(new java.awt.Color(204, 204, 204));
        jLabelDepManagement.setText("Gestió Departaments");

        javax.swing.GroupLayout jPanelDepManagementLayout = new javax.swing.GroupLayout(jPanelDepManagement);
        jPanelDepManagement.setLayout(jPanelDepManagementLayout);
        jPanelDepManagementLayout.setHorizontalGroup(
            jPanelDepManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDepManagementLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelDepManagement)
                .addContainerGap(636, Short.MAX_VALUE))
        );
        jPanelDepManagementLayout.setVerticalGroup(
            jPanelDepManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDepManagementLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelDepManagement)
                .addContainerGap(529, Short.MAX_VALUE))
        );

        jPaneMenuRight.add(jPanelDepManagement, "card4");

        jPanelMessage.setBackground(new java.awt.Color(51, 51, 51));

        jLabelMessage.setBackground(new java.awt.Color(55, 55, 55));
        jLabelMessage.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabelMessage.setForeground(new java.awt.Color(204, 204, 204));
        jLabelMessage.setText("Missatges");

        javax.swing.GroupLayout jPanelMessageLayout = new javax.swing.GroupLayout(jPanelMessage);
        jPanelMessage.setLayout(jPanelMessageLayout);
        jPanelMessageLayout.setHorizontalGroup(
            jPanelMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMessageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelMessage)
                .addContainerGap(721, Short.MAX_VALUE))
        );
        jPanelMessageLayout.setVerticalGroup(
            jPanelMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMessageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelMessage)
                .addContainerGap(529, Short.MAX_VALUE))
        );

        jPaneMenuRight.add(jPanelMessage, "card7");

        jPanelSettings.setBackground(new java.awt.Color(51, 51, 51));

        jLabelSettings.setBackground(new java.awt.Color(55, 55, 55));
        jLabelSettings.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabelSettings.setForeground(new java.awt.Color(204, 204, 204));
        jLabelSettings.setText("Configuració");

        jLabelTheme.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabelTheme.setForeground(new java.awt.Color(204, 204, 204));
        jLabelTheme.setText("Tema del aplicatiu");

        jLabelLight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ModeClar.png"))); // NOI18N
        jLabelLight.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabelDark.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ModeFosc.png"))); // NOI18N
        jLabelDark.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanelSettingsLayout = new javax.swing.GroupLayout(jPanelSettings);
        jPanelSettings.setLayout(jPanelSettingsLayout);
        jPanelSettingsLayout.setHorizontalGroup(
            jPanelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSettingsLayout.createSequentialGroup()
                .addGroup(jPanelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSettingsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelSettings))
                    .addGroup(jPanelSettingsLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelSettingsLayout.createSequentialGroup()
                                .addComponent(jLabelLight)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelDark))
                            .addComponent(jLabelTheme))))
                .addContainerGap(652, Short.MAX_VALUE))
        );
        jPanelSettingsLayout.setVerticalGroup(
            jPanelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSettingsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSettings)
                .addGap(25, 25, 25)
                .addComponent(jLabelTheme)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelLight)
                    .addComponent(jLabelDark))
                .addContainerGap(422, Short.MAX_VALUE))
        );

        jPaneMenuRight.add(jPanelSettings, "card8");

        getContentPane().add(jPaneMenuRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 800, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     *
     * @param evt Fa petició de Logout al Servidor Tanca la finestra del Client
     * d'Escriptori
     */
    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked

        logOut();
        System.exit(0);

    }//GEN-LAST:event_jLabelCloseMouseClicked

    /**
     *
     * @param evt Minimitza la pantalla a la barra de tasques del sistema
     */
    private void jLabelMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizeMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jLabelMinimizeMouseClicked

    /**
     *
     * @param evt Fa petició de Logout al Servidor Tanca la finestra del Client
     * d'Escriptori Fa visible la finestra de Login
     */
    private void jLabelDisconnectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDisconnectMouseClicked
        Login window = new Login();
        window.setVisible(true);
        logOut();
        this.dispose();
    }//GEN-LAST:event_jLabelDisconnectMouseClicked

    /**
     *
     * @param evt Fa visible el menú d'Inici
     */
    private void jLabelHomeMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHomeMenuMouseClicked
        jLabelHomeMenu.setBackground(new java.awt.Color(51, 51, 51));
        jLabelHomeMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/01 Inici Selected.png")));
        jPanelHome.setVisible(true);

        jLabelTicketsMenu.setBackground(new java.awt.Color(55, 55, 55));
        jLabelTicketsMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/02 Tiquets NoSelected.png")));
        jPanelTickets.setVisible(false);
        jLabelStadisticsMenu.setBackground(new java.awt.Color(55, 55, 55));
        jLabelStadisticsMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/04 Estadistiques NoSelected.png")));
        jPanelStadistics.setVisible(false);
        jLabelUserManagementMenu.setBackground(new java.awt.Color(55, 55, 55));
        jLabelUserManagementMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/05 Gestio Usuaris NoSelected.png")));
        jPanelUserManagement.setVisible(false);
        jLabelDepManagementMenu.setBackground(new java.awt.Color(55, 55, 55));
        jLabelDepManagementMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/08 Departaments NoSelected.png")));
        jPanelDepManagement.setVisible(false);
        jLabelMessageMenu.setBackground(new java.awt.Color(55, 55, 55));
        jLabelMessageMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/06 Missatges NoSelected.png")));
        jPanelMessage.setVisible(false);
        jLabelSettingsMenu.setBackground(new java.awt.Color(55, 55, 55));
        jLabelSettingsMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/07 Configuracio NoSelected.png")));
        jPanelSettings.setVisible(false);
    }//GEN-LAST:event_jLabelHomeMenuMouseClicked

    /**
     *
     * @param evt Fa visible el menú de Tiquets
     */
    private void jLabelTicketsMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTicketsMenuMouseClicked
        jLabelHomeMenu.setBackground(new java.awt.Color(55, 55, 55));
        jLabelHomeMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/01 Inici NoSelected.png")));
        jPanelHome.setVisible(false);

        jLabelTicketsMenu.setBackground(new java.awt.Color(51, 51, 51));
        jLabelTicketsMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/02 Tiquets Selected.png")));
        jPanelTickets.setVisible(true);

        jLabelStadisticsMenu.setBackground(new java.awt.Color(55, 55, 55));
        jLabelStadisticsMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/04 Estadistiques NoSelected.png")));
        jPanelStadistics.setVisible(false);
        jLabelUserManagementMenu.setBackground(new java.awt.Color(55, 55, 55));
        jLabelUserManagementMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/05 Gestio Usuaris NoSelected.png")));
        jPanelUserManagement.setVisible(false);
        jLabelDepManagementMenu.setBackground(new java.awt.Color(55, 55, 55));
        jLabelDepManagementMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/08 Departaments NoSelected.png")));
        jPanelDepManagement.setVisible(false);
        jLabelMessageMenu.setBackground(new java.awt.Color(55, 55, 55));
        jLabelMessageMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/06 Missatges NoSelected.png")));
        jPanelMessage.setVisible(false);
        jLabelSettingsMenu.setBackground(new java.awt.Color(55, 55, 55));
        jLabelSettingsMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/07 Configuracio NoSelected.png")));
        jPanelSettings.setVisible(false);
    }//GEN-LAST:event_jLabelTicketsMenuMouseClicked

    /**
     *
     * @param evt Fa visible el menú d'Estadístiques
     */
    private void jLabelStadisticsMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelStadisticsMenuMouseClicked
        jLabelHomeMenu.setBackground(new java.awt.Color(55, 55, 55));
        jLabelHomeMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/01 Inici NoSelected.png")));
        jPanelHome.setVisible(false);
        jLabelTicketsMenu.setBackground(new java.awt.Color(55, 55, 55));
        jLabelTicketsMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/02 Tiquets NoSelected.png")));
        jPanelTickets.setVisible(false);

        jLabelStadisticsMenu.setBackground(new java.awt.Color(51, 51, 51));
        jLabelStadisticsMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/04 Estadistiques Selected.png")));
        jPanelStadistics.setVisible(true);

        jLabelUserManagementMenu.setBackground(new java.awt.Color(55, 55, 55));
        jLabelUserManagementMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/05 Gestio Usuaris NoSelected.png")));
        jPanelUserManagement.setVisible(false);
        jLabelDepManagementMenu.setBackground(new java.awt.Color(55, 55, 55));
        jLabelDepManagementMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/08 Departaments NoSelected.png")));
        jPanelDepManagement.setVisible(false);
        jLabelMessageMenu.setBackground(new java.awt.Color(55, 55, 55));
        jLabelMessageMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/06 Missatges NoSelected.png")));
        jPanelMessage.setVisible(false);
        jLabelSettingsMenu.setBackground(new java.awt.Color(55, 55, 55));
        jLabelSettingsMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/07 Configuracio NoSelected.png")));
        jPanelSettings.setVisible(false);
    }//GEN-LAST:event_jLabelStadisticsMenuMouseClicked

    /**
     *
     * @param evt Fa visible el menú de Gestió d'Usuaris
     */
    private void jLabelUserManagementMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelUserManagementMenuMouseClicked
        jLabelHomeMenu.setBackground(new java.awt.Color(55, 55, 55));
        jLabelHomeMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/01 Inici NoSelected.png")));
        jPanelHome.setVisible(false);
        jLabelTicketsMenu.setBackground(new java.awt.Color(55, 55, 55));
        jLabelTicketsMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/02 Tiquets NoSelected.png")));
        jPanelTickets.setVisible(false);
        jLabelStadisticsMenu.setBackground(new java.awt.Color(55, 55, 55));
        jLabelStadisticsMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/04 Estadistiques NoSelected.png")));
        jPanelStadistics.setVisible(false);

        jLabelUserManagementMenu.setBackground(new java.awt.Color(51, 51, 51));
        jLabelUserManagementMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/05 Gestio Usuaris Selected.png")));
        jPanelUserManagement.setVisible(true);

        jLabelDepManagementMenu.setBackground(new java.awt.Color(55, 55, 55));
        jLabelDepManagementMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/08 Departaments NoSelected.png")));
        jPanelDepManagement.setVisible(false);
        jLabelMessageMenu.setBackground(new java.awt.Color(55, 55, 55));
        jLabelMessageMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/06 Missatges NoSelected.png")));
        jPanelMessage.setVisible(false);
        jLabelSettingsMenu.setBackground(new java.awt.Color(55, 55, 55));
        jLabelSettingsMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/07 Configuracio NoSelected.png")));
        jPanelSettings.setVisible(false);

        jPanelUsers.setVisible(true);
        jPanelUsersAdd.setVisible(false);
        
        listUsers();
    }//GEN-LAST:event_jLabelUserManagementMenuMouseClicked

    /**
     *
     * @param evt Fa visible el menú de Missatges
     */
    private void jLabelMessageMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMessageMenuMouseClicked
        jLabelHomeMenu.setBackground(new java.awt.Color(55, 55, 55));
        jLabelHomeMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/01 Inici NoSelected.png")));
        jPanelHome.setVisible(false);
        jLabelTicketsMenu.setBackground(new java.awt.Color(55, 55, 55));
        jLabelTicketsMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/02 Tiquets NoSelected.png")));
        jPanelTickets.setVisible(false);
        jLabelStadisticsMenu.setBackground(new java.awt.Color(55, 55, 55));
        jLabelStadisticsMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/04 Estadistiques NoSelected.png")));
        jPanelStadistics.setVisible(false);
        jLabelUserManagementMenu.setBackground(new java.awt.Color(55, 55, 55));
        jLabelUserManagementMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/05 Gestio Usuaris NoSelected.png")));
        jPanelUserManagement.setVisible(false);
        jLabelDepManagementMenu.setBackground(new java.awt.Color(55, 55, 55));
        jLabelDepManagementMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/08 Departaments NoSelected.png")));
        jPanelDepManagement.setVisible(false);

        jLabelMessageMenu.setBackground(new java.awt.Color(51, 51, 51));
        jLabelMessageMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/06 Missatges Selected.png")));
        jPanelMessage.setVisible(true);

        jLabelSettingsMenu.setBackground(new java.awt.Color(55, 55, 55));
        jLabelSettingsMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/07 Configuracio NoSelected.png")));
        jPanelSettings.setVisible(false);
    }//GEN-LAST:event_jLabelMessageMenuMouseClicked

    /**
     *
     * @param evt Fa visible el menú de Configuració
     */
    private void jLabelSettingsMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSettingsMenuMouseClicked
        jLabelHomeMenu.setBackground(new java.awt.Color(55, 55, 55));
        jLabelHomeMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/01 Inici NoSelected.png")));
        jPanelHome.setVisible(false);
        jLabelTicketsMenu.setBackground(new java.awt.Color(55, 55, 55));
        jLabelTicketsMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/02 Tiquets NoSelected.png")));
        jPanelTickets.setVisible(false);
        jLabelStadisticsMenu.setBackground(new java.awt.Color(55, 55, 55));
        jLabelStadisticsMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/04 Estadistiques NoSelected.png")));
        jPanelStadistics.setVisible(false);
        jLabelUserManagementMenu.setBackground(new java.awt.Color(55, 55, 55));
        jLabelUserManagementMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/05 Gestio Usuaris NoSelected.png")));
        jPanelUserManagement.setVisible(false);
        jLabelDepManagementMenu.setBackground(new java.awt.Color(55, 55, 55));
        jLabelDepManagementMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/08 Departaments NoSelected.png")));
        jPanelDepManagement.setVisible(false);
        jLabelMessageMenu.setBackground(new java.awt.Color(55, 55, 55));
        jLabelMessageMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/06 Missatges NoSelected.png")));
        jPanelMessage.setVisible(false);

        jLabelSettingsMenu.setBackground(new java.awt.Color(51, 51, 51));
        jLabelSettingsMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/07 Configuracio Selected.png")));
        jPanelSettings.setVisible(true);
    }//GEN-LAST:event_jLabelSettingsMenuMouseClicked

    /**
     *
     * @param evt Obre la finestra amb el formulari d'alta d'un usuari nou
     */
    private void jLabelNewUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelNewUserMouseClicked
        jPanelUsers.setVisible(false);
        jPanelUsersAdd.setVisible(true);
    }//GEN-LAST:event_jLabelNewUserMouseClicked

    /**
     *
     * @param evt Fa visible el menú de Departament
     */
    private void jLabelDepManagementMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDepManagementMenuMouseClicked
        jLabelHomeMenu.setBackground(new java.awt.Color(55, 55, 55));
        jLabelHomeMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/01 Inici NoSelected.png")));
        jPanelHome.setVisible(false);
        jLabelTicketsMenu.setBackground(new java.awt.Color(55, 55, 55));
        jLabelTicketsMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/02 Tiquets NoSelected.png")));
        jPanelTickets.setVisible(false);
        jLabelStadisticsMenu.setBackground(new java.awt.Color(55, 55, 55));
        jLabelStadisticsMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/04 Estadistiques NoSelected.png")));
        jPanelStadistics.setVisible(false);
        jLabelUserManagementMenu.setBackground(new java.awt.Color(55, 55, 55));
        jLabelUserManagementMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/05 Gestio Usuaris NoSelected.png")));
        jPanelUserManagement.setVisible(false);

        jLabelDepManagementMenu.setBackground(new java.awt.Color(51, 51, 51));
        jLabelDepManagementMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/08 Departaments Selected.png")));
        jPanelDepManagement.setVisible(true);

        jLabelMessageMenu.setBackground(new java.awt.Color(55, 55, 55));
        jLabelMessageMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/06 Missatges NoSelected.png")));
        jPanelMessage.setVisible(false);
        jLabelSettingsMenu.setBackground(new java.awt.Color(55, 55, 55));
        jLabelSettingsMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/07 Configuracio NoSelected.png")));
        jPanelSettings.setVisible(false);
    }//GEN-LAST:event_jLabelDepManagementMenuMouseClicked

    /**
     *
     * @param evt Icona de fletxa per tornar a enrerre de la pantalla d'alta
     * d'usuari a la de gestió d'usuaris
     */
    private void jLabelBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBackMouseClicked
        jPanelUsers.setVisible(true);
        jPanelUsersAdd.setVisible(false);
    }//GEN-LAST:event_jLabelBackMouseClicked

    /**
     *
     * @param evt Neteja els camps del formulari d'alta d'usuari
     */
    private void jLabelCleanAddPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCleanAddPanelMouseClicked
        cleanFormAdd();
    }//GEN-LAST:event_jLabelCleanAddPanelMouseClicked

    private void jLabelUserAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelUserAddMouseClicked
        //Creo les variables on guardo les dades del formulari

        String user = jTextFieldAddUser.getText().toString();
        String password = jPasswordFieldAddPwd.getText().toString();
        String name = jTextFieldAddName.getText().toString();
        String lastname = jTextFieldAddLastname.getText().toString();
        String department = jComboBoxAddDepartment.getSelectedItem().toString();
        String role = jComboBoxAddRole.getSelectedItem().toString();
        String state = jComboBoxAddState.getSelectedItem().toString();

        //Creo instancia de la clase GestioUsuarisUtils
        GestioUsuarisUtils guu = new GestioUsuarisUtils();

        guu.setUser(user);
        guu.setPassword(password);
        guu.setName(name);
        guu.setLastname(lastname);
        guu.setDepartment(department);
        guu.setRole(role);
        guu.setState(state);

        guu.altaUsuari();

        cleanFormAdd();

    }//GEN-LAST:event_jLabelUserAddMouseClicked

    private void jLabelSearchUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSearchUsersMouseClicked
        listUsers();
    }//GEN-LAST:event_jLabelSearchUsersMouseClicked

    private void jLabelDelUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDelUsersMouseClicked
        deleteUsers();
    }//GEN-LAST:event_jLabelDelUsersMouseClicked

    private void jButtonRefreshListUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshListUsersActionPerformed
        filtraryRefrescar();
    }//GEN-LAST:event_jButtonRefreshListUsersActionPerformed

    private void jButtonDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteUserActionPerformed
        deleteUsers();
    }//GEN-LAST:event_jButtonDeleteUserActionPerformed

    private void jButtonRefreshListUsers1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshListUsers1ActionPerformed
        filtraryRefrescar();
    }//GEN-LAST:event_jButtonRefreshListUsers1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DesktopAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DesktopAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DesktopAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DesktopAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DesktopAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDeleteUser;
    private javax.swing.JButton jButtonRefreshListUsers;
    private javax.swing.JButton jButtonRefreshListUsers1;
    private javax.swing.JComboBox<String> jComboBoxAddDepartment;
    private javax.swing.JComboBox<String> jComboBoxAddRole;
    private javax.swing.JComboBox<String> jComboBoxAddState;
    private javax.swing.JComboBox<String> jComboBoxFiltraUsersRol;
    private javax.swing.JLabel jLabelAddDepartment;
    private javax.swing.JLabel jLabelAddLastname;
    private javax.swing.JLabel jLabelAddName;
    private javax.swing.JLabel jLabelAddPwd;
    private javax.swing.JLabel jLabelAddRole;
    private javax.swing.JLabel jLabelAddUser;
    private javax.swing.JLabel jLabelBack;
    private javax.swing.JLabel jLabelCleanAddPanel;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelDark;
    private javax.swing.JLabel jLabelDelUsers;
    private javax.swing.JLabel jLabelDepManagement;
    public javax.swing.JLabel jLabelDepManagementMenu;
    public javax.swing.JLabel jLabelDisconnect;
    private javax.swing.JLabel jLabelHome;
    public javax.swing.JLabel jLabelHomeMenu;
    private javax.swing.JLabel jLabelLight;
    private javax.swing.JLabel jLabelMessage;
    public javax.swing.JLabel jLabelMessageMenu;
    private javax.swing.JLabel jLabelMinimize;
    private javax.swing.JLabel jLabelModifyUsers;
    private javax.swing.JLabel jLabelNewUser;
    private javax.swing.JLabel jLabelSearchUsers;
    private javax.swing.JLabel jLabelSettings;
    public javax.swing.JLabel jLabelSettingsMenu;
    private javax.swing.JLabel jLabelStadistics;
    public javax.swing.JLabel jLabelStadisticsMenu;
    private javax.swing.JLabel jLabelState;
    private javax.swing.JLabel jLabelTheme;
    private javax.swing.JLabel jLabelTickets;
    public javax.swing.JLabel jLabelTicketsMenu;
    private javax.swing.JLabel jLabelTittle;
    private javax.swing.JLabel jLabelUserAdd;
    public javax.swing.JLabel jLabelUserConnected;
    private javax.swing.JLabel jLabelUserIcon;
    public javax.swing.JLabel jLabelUserManagementMenu;
    private javax.swing.JLabel jLabelUsers;
    private javax.swing.JPanel jPaneMenuRight;
    public javax.swing.JPanel jPanelDepManagement;
    public javax.swing.JPanel jPanelHome;
    private javax.swing.JPanel jPanelLogo;
    private javax.swing.JPanel jPanelMenuLeft;
    public javax.swing.JPanel jPanelMessage;
    public javax.swing.JPanel jPanelSettings;
    public javax.swing.JPanel jPanelStadistics;
    public javax.swing.JPanel jPanelTickets;
    private javax.swing.JPanel jPanelTop;
    public javax.swing.JPanel jPanelUserManagement;
    private javax.swing.JPanel jPanelUsers;
    private javax.swing.JPanel jPanelUsersAdd;
    private javax.swing.JPasswordField jPasswordFieldAddPwd;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JTable jTableUsers;
    private javax.swing.JTextField jTextFieldAddLastname;
    private javax.swing.JTextField jTextFieldAddName;
    private javax.swing.JTextField jTextFieldAddUser;
    // End of variables declaration//GEN-END:variables

    /**
     * @param usuari
     * @param pwd
     * @param id Envia la petició de logout al servidor
     */
    private void logOut() {

        Socket sc;
        try {
            sc = new Socket("127.0.0.1", 5000);
            DataInputStream in = new DataInputStream(sc.getInputStream());
            DataOutputStream out = new DataOutputStream(sc.getOutputStream());

            // Llegir la resposta del servidor al establir la connexió
            String resposta_svr = in.readUTF();
            //Enviem resposta al servidor amb el usuari i la contrasenya
            out.writeUTF("LOGIN," + getUsuari() + "," + getPwd() + "," + getId());
            //Executo la consulta de la crida per sortir
            out.writeUTF("USER_EXIT");
            System.out.println("Valor getId: " + getId());

        } catch (IOException ex) {
            Logger.getLogger(DesktopAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void listUsers() {

        Socket sc;
        try {
            sc = new Socket("127.0.0.1", 5000);
            DataInputStream in = new DataInputStream(sc.getInputStream());
            DataOutputStream out = new DataOutputStream(sc.getOutputStream());

            //Llegir la resposta del servidor al establir la connexió
            String resposta_svr = in.readUTF();

            //Enviem resposta al servidor amb el usuari i la contrasenya i el ID obtingut login
            out.writeUTF("LOGIN," + getUsuari() + "," + getPwd() + "," + getId());

            //Executem la crida per llistar usuaris
            out.writeUTF("USER_QUERY,SELECT * FROM usuaris ORDER BY usuari");

            // Llegir la resposta del servidor del nombre de registres trobats
            int registres_trobats = in.readInt();

            String[] nomColumnes = {"ID", "Usuari", "Contrasenya", "Nom", "Cognoms", "Departament", "Rol", "Estat"};
            String[] camps;
            Object[][] registresGrid = new Object[registres_trobats][8];

            DefaultTableModel model = new DefaultTableModel();
            model.setColumnIdentifiers(nomColumnes);

            for (int i = 0; i < registres_trobats; i++) {
                //llistaUsuaris.add(in.readUTF());
                String registre = in.readUTF();
                camps = registre.split(",");

                for (int j = 0; j < 0; j++) {
                    registresGrid[i][j] = camps[j];
                }

                model.addRow(camps);
            }

            jTableUsers.setModel(model);

        } catch (Exception e) {
        }
    }
    
    private void listUsersAdmin() {

        Socket sc;
        try {
            sc = new Socket("127.0.0.1", 5000);
            DataInputStream in = new DataInputStream(sc.getInputStream());
            DataOutputStream out = new DataOutputStream(sc.getOutputStream());

            //Llegir la resposta del servidor al establir la connexió
            String resposta_svr = in.readUTF();

            //Enviem resposta al servidor amb el usuari i la contrasenya i el ID obtingut login
            out.writeUTF("LOGIN," + getUsuari() + "," + getPwd() + "," + getId());

            //Executem la crida per llistar usuaris
            out.writeUTF("USER_QUERY,SELECT * FROM usuaris WHERE rol='1' ORDER BY usuari");

            // Llegir la resposta del servidor del nombre de registres trobats
            int registres_trobats = in.readInt();

            String[] nomColumnes = {"ID", "Usuari", "Contrasenya", "Nom", "Cognoms", "Departament", "Rol", "Estat"};
            String[] camps;
            Object[][] registresGrid = new Object[registres_trobats][8];

            DefaultTableModel model = new DefaultTableModel();
            model.setColumnIdentifiers(nomColumnes);

            for (int i = 0; i < registres_trobats; i++) {
                //llistaUsuaris.add(in.readUTF());
                String registre = in.readUTF();
                camps = registre.split(",");

                for (int j = 0; j < 0; j++) {
                    registresGrid[i][j] = camps[j];
                }

                model.addRow(camps);
            }

            jTableUsers.setModel(model);

        } catch (Exception e) {
        }
    }
    
    private void listUsersTecnics() {

        Socket sc;
        try {
            sc = new Socket("127.0.0.1", 5000);
            DataInputStream in = new DataInputStream(sc.getInputStream());
            DataOutputStream out = new DataOutputStream(sc.getOutputStream());

            //Llegir la resposta del servidor al establir la connexió
            String resposta_svr = in.readUTF();

            //Enviem resposta al servidor amb el usuari i la contrasenya i el ID obtingut login
            out.writeUTF("LOGIN," + getUsuari() + "," + getPwd() + "," + getId());

            //Executem la crida per llistar usuaris
            out.writeUTF("USER_QUERY,SELECT * FROM usuaris WHERE rol='2' ORDER BY usuari");

            // Llegir la resposta del servidor del nombre de registres trobats
            int registres_trobats = in.readInt();

            String[] nomColumnes = {"ID", "Usuari", "Contrasenya", "Nom", "Cognoms", "Departament", "Rol", "Estat"};
            String[] camps;
            Object[][] registresGrid = new Object[registres_trobats][8];

            DefaultTableModel model = new DefaultTableModel();
            model.setColumnIdentifiers(nomColumnes);

            for (int i = 0; i < registres_trobats; i++) {
                //llistaUsuaris.add(in.readUTF());
                String registre = in.readUTF();
                camps = registre.split(",");

                for (int j = 0; j < 0; j++) {
                    registresGrid[i][j] = camps[j];
                }

                model.addRow(camps);
            }

            jTableUsers.setModel(model);

        } catch (Exception e) {
        }
    }
    
    private void listUsersUsuaris() {

        Socket sc;
        try {
            sc = new Socket("127.0.0.1", 5000);
            DataInputStream in = new DataInputStream(sc.getInputStream());
            DataOutputStream out = new DataOutputStream(sc.getOutputStream());

            //Llegir la resposta del servidor al establir la connexió
            String resposta_svr = in.readUTF();

            //Enviem resposta al servidor amb el usuari i la contrasenya i el ID obtingut login
            out.writeUTF("LOGIN," + getUsuari() + "," + getPwd() + "," + getId());

            //Executem la crida per llistar usuaris
            out.writeUTF("USER_QUERY,SELECT * FROM usuaris WHERE rol='3' ORDER BY usuari");

            // Llegir la resposta del servidor del nombre de registres trobats
            int registres_trobats = in.readInt();

            String[] nomColumnes = {"ID", "Usuari", "Contrasenya", "Nom", "Cognoms", "Departament", "Rol", "Estat"};
            String[] camps;
            Object[][] registresGrid = new Object[registres_trobats][8];

            DefaultTableModel model = new DefaultTableModel();
            model.setColumnIdentifiers(nomColumnes);

            for (int i = 0; i < registres_trobats; i++) {
                //llistaUsuaris.add(in.readUTF());
                String registre = in.readUTF();
                camps = registre.split(",");

                for (int j = 0; j < 0; j++) {
                    registresGrid[i][j] = camps[j];
                }

                model.addRow(camps);
            }

            jTableUsers.setModel(model);

        } catch (Exception e) {
        }
    }
    
    private void filtraryRefrescar(){
        int rolUsuari = jComboBoxFiltraUsersRol.getSelectedIndex();
        
        switch(rolUsuari){
            //Administradors
            case 1:
                if (rolUsuari == 1){
                    listUsersAdmin();
                }
                jComboBoxFiltraUsersRol.setSelectedIndex(1);
                break;
            //Administradors
            case 2:
                if (rolUsuari == 2){
                    listUsersTecnics();
                }
                jComboBoxFiltraUsersRol.setSelectedIndex(2);
                break;
            //Administradors
            case 3:
                if (rolUsuari == 3){
                    listUsersUsuaris();
                }
                jComboBoxFiltraUsersRol.setSelectedIndex(3);
                break;
            default:
                listUsers();
                jComboBoxFiltraUsersRol.setSelectedIndex(0);
        }
    }

    private void deleteUsers() {

        int fila = jTableUsers.getSelectedRow();
        String valor = jTableUsers.getValueAt(fila, 0).toString();

        Socket sc;
        try {
            sc = new Socket("127.0.0.1", 5000);
            DataInputStream in = new DataInputStream(sc.getInputStream());
            DataOutputStream out = new DataOutputStream(sc.getOutputStream());

            //Llegir la resposta del servidor al establir la connexió
            String resposta_svr = in.readUTF();

            //Enviem resposta al servidor amb el usuari i la contrasenya i el ID obtingut login
            out.writeUTF("LOGIN," + getUsuari() + "," + getPwd() + "," + getId());

            //Executem la crida per llistar usuaris
            out.writeUTF("USER_DELETE," + valor);

            // Llegir la resposta del servidor del nombre de registres trobats
            int resposta_eliminar = in.readInt();
            
            if (resposta_eliminar == 1) {
                filtraryRefrescar();
            }

        } catch (Exception e) {
        }

    }

    //Object[] ob = new Object[7];
    private void cleanFormAdd() {
        jTextFieldAddUser.setText(null);
        jPasswordFieldAddPwd.setText(null);
        jTextFieldAddName.setText(null);
        jTextFieldAddLastname.setText(null);
        jComboBoxAddDepartment.setSelectedIndex(0);
        jComboBoxAddRole.setSelectedIndex(0);
        jComboBoxAddState.setSelectedIndex(0);
    }
}
