/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Plantillas.*;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Garcia_D
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        jPanelFosc.setVisible(true);
        jPanelClar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelLeft = new javax.swing.JPanel();
        jLabelLogo = new javax.swing.JLabel();
        jLabelClar = new javax.swing.JLabel();
        jLabelFosc = new javax.swing.JLabel();
        jPanelRight = new javax.swing.JPanel();
        jPanelFosc = new javax.swing.JPanel();
        jLabelCloseFosc = new javax.swing.JLabel();
        loginTextIniciarFosc = new javax.swing.JLabel();
        jLabelUserFosc = new javax.swing.JLabel();
        jLabelUserIconFosc = new javax.swing.JLabel();
        jTextFieldUserFosc = new javax.swing.JTextField();
        jSeparatorUserFosc = new javax.swing.JSeparator();
        jLabelPasswordFosc = new javax.swing.JLabel();
        jLabelPasswordIconFosc = new javax.swing.JLabel();
        jPasswordFieldFosc = new javax.swing.JPasswordField();
        jSeparatorPasswordFosc = new javax.swing.JSeparator();
        jLabelLoginFosc = new javax.swing.JLabel();
        jPanelClar = new javax.swing.JPanel();
        jLabelCloseClar = new javax.swing.JLabel();
        loginTextIniciarSesionClar = new javax.swing.JLabel();
        jLabelUserClar = new javax.swing.JLabel();
        jLabelUserIconClar = new javax.swing.JLabel();
        jTextFieldUserClar = new javax.swing.JTextField();
        jSeparatorUserClar = new javax.swing.JSeparator();
        jLabelPasswordClar = new javax.swing.JLabel();
        jLabelPasswordIconClar = new javax.swing.JLabel();
        jPasswordFieldClar = new javax.swing.JPasswordField();
        jSeparatorPasswordClar = new javax.swing.JSeparator();
        jLabelLoginClar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelLeft.setBackground(new java.awt.Color(73, 181, 172));

        jLabelLogo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelLogo.setForeground(new java.awt.Color(51, 51, 51));
        jLabelLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLogo.setText("LOGO APLICATIU");

        jLabelClar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-sun-24.png"))); // NOI18N
        jLabelClar.setToolTipText("Mode Clar");
        jLabelClar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelClarMouseClicked(evt);
            }
        });

        jLabelFosc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-do-not-disturb-ios-24.png"))); // NOI18N
        jLabelFosc.setToolTipText("Mode Fosc");
        jLabelFosc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelFosc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelFoscMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelLeftLayout = new javax.swing.GroupLayout(jPanelLeft);
        jPanelLeft.setLayout(jPanelLeftLayout);
        jPanelLeftLayout.setHorizontalGroup(
            jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLeftLayout.createSequentialGroup()
                .addGroup(jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLeftLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelLeftLayout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jLabelClar)
                        .addGap(20, 20, 20)
                        .addComponent(jLabelFosc)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanelLeftLayout.setVerticalGroup(
            jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLeftLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 361, Short.MAX_VALUE)
                .addGroup(jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelClar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelFosc, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(20, 20, 20))
        );

        getContentPane().add(jPanelLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 600));

        jPanelRight.setLayout(new java.awt.CardLayout());

        jPanelFosc.setBackground(new java.awt.Color(51, 51, 51));

        jLabelCloseFosc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-close-24.png"))); // NOI18N
        jLabelCloseFosc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelCloseFosc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseFoscMouseClicked(evt);
            }
        });

        loginTextIniciarFosc.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        loginTextIniciarFosc.setForeground(new java.awt.Color(204, 204, 204));
        loginTextIniciarFosc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginTextIniciarFosc.setText("Iniciar Sessió");

        jLabelUserFosc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelUserFosc.setForeground(new java.awt.Color(204, 204, 204));
        jLabelUserFosc.setText("USUARI");

        jLabelUserIconFosc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_male_user_40px_1.png"))); // NOI18N
        jLabelUserIconFosc.setText("jLabel5");

        jTextFieldUserFosc.setBackground(new java.awt.Color(51, 51, 51));
        jTextFieldUserFosc.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jTextFieldUserFosc.setForeground(new java.awt.Color(204, 204, 204));
        jTextFieldUserFosc.setBorder(null);

        jSeparatorUserFosc.setBackground(new java.awt.Color(73, 181, 172));
        jSeparatorUserFosc.setForeground(new java.awt.Color(73, 181, 172));

        jLabelPasswordFosc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelPasswordFosc.setForeground(new java.awt.Color(204, 204, 204));
        jLabelPasswordFosc.setText("CONTRASENYA");

        jLabelPasswordIconFosc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_lock_40px.png"))); // NOI18N
        jLabelPasswordIconFosc.setText("jLabel5");

        jPasswordFieldFosc.setBackground(new java.awt.Color(51, 51, 51));
        jPasswordFieldFosc.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jPasswordFieldFosc.setForeground(new java.awt.Color(204, 204, 204));
        jPasswordFieldFosc.setBorder(null);

        jSeparatorPasswordFosc.setBackground(new java.awt.Color(73, 181, 172));
        jSeparatorPasswordFosc.setForeground(new java.awt.Color(73, 181, 172));

        jLabelLoginFosc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-enter-40.png"))); // NOI18N
        jLabelLoginFosc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelLoginFosc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLoginFoscMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelFoscLayout = new javax.swing.GroupLayout(jPanelFosc);
        jPanelFosc.setLayout(jPanelFoscLayout);
        jPanelFoscLayout.setHorizontalGroup(
            jPanelFoscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFoscLayout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(jPanelFoscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFoscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanelFoscLayout.createSequentialGroup()
                            .addComponent(jLabelPasswordIconFosc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPasswordFieldFosc, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jSeparatorPasswordFosc, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelPasswordFosc)
                    .addComponent(loginTextIniciarFosc)
                    .addGroup(jPanelFoscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabelUserFosc, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelFoscLayout.createSequentialGroup()
                            .addComponent(jLabelUserIconFosc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldUserFosc, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jSeparatorUserFosc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFoscLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelCloseFosc)
                .addContainerGap())
            .addGroup(jPanelFoscLayout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(jLabelLoginFosc)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelFoscLayout.setVerticalGroup(
            jPanelFoscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFoscLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCloseFosc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginTextIniciarFosc, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(jLabelUserFosc)
                .addGap(18, 18, 18)
                .addGroup(jPanelFoscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUserIconFosc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldUserFosc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparatorUserFosc, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabelPasswordFosc)
                .addGap(18, 18, 18)
                .addGroup(jPanelFoscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPasswordIconFosc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordFieldFosc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparatorPasswordFosc, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(jLabelLoginFosc)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        jPanelRight.add(jPanelFosc, "card2");

        jPanelClar.setBackground(new java.awt.Color(204, 204, 204));

        jLabelCloseClar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-close-24.png"))); // NOI18N
        jLabelCloseClar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelCloseClar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseClarMouseClicked(evt);
            }
        });

        loginTextIniciarSesionClar.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        loginTextIniciarSesionClar.setForeground(new java.awt.Color(51, 51, 51));
        loginTextIniciarSesionClar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginTextIniciarSesionClar.setText("Iniciar Sessió");

        jLabelUserClar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelUserClar.setForeground(new java.awt.Color(51, 51, 51));
        jLabelUserClar.setText("USUARI");

        jLabelUserIconClar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_male_user_40px_1.png"))); // NOI18N
        jLabelUserIconClar.setText("jLabel5");

        jTextFieldUserClar.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldUserClar.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jTextFieldUserClar.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldUserClar.setBorder(null);

        jSeparatorUserClar.setBackground(new java.awt.Color(73, 181, 172));
        jSeparatorUserClar.setForeground(new java.awt.Color(73, 181, 172));

        jLabelPasswordClar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelPasswordClar.setForeground(new java.awt.Color(51, 51, 51));
        jLabelPasswordClar.setText("CONTRASENYA");

        jLabelPasswordIconClar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_lock_40px.png"))); // NOI18N
        jLabelPasswordIconClar.setText("jLabel5");

        jPasswordFieldClar.setBackground(new java.awt.Color(204, 204, 204));
        jPasswordFieldClar.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jPasswordFieldClar.setForeground(new java.awt.Color(51, 51, 51));
        jPasswordFieldClar.setBorder(null);

        jSeparatorPasswordClar.setBackground(new java.awt.Color(73, 181, 172));
        jSeparatorPasswordClar.setForeground(new java.awt.Color(73, 181, 172));

        jLabelLoginClar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-enter-40.png"))); // NOI18N
        jLabelLoginClar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelLoginClar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLoginClarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelClarLayout = new javax.swing.GroupLayout(jPanelClar);
        jPanelClar.setLayout(jPanelClarLayout);
        jPanelClarLayout.setHorizontalGroup(
            jPanelClarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClarLayout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(jPanelClarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelClarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanelClarLayout.createSequentialGroup()
                            .addComponent(jLabelPasswordIconClar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPasswordFieldClar, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jSeparatorPasswordClar, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelPasswordClar)
                    .addComponent(loginTextIniciarSesionClar)
                    .addGroup(jPanelClarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabelUserClar, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelClarLayout.createSequentialGroup()
                            .addComponent(jLabelUserIconClar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldUserClar, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jSeparatorUserClar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelClarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelCloseClar)
                .addContainerGap())
            .addGroup(jPanelClarLayout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(jLabelLoginClar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelClarLayout.setVerticalGroup(
            jPanelClarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCloseClar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginTextIniciarSesionClar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(jLabelUserClar)
                .addGap(18, 18, 18)
                .addGroup(jPanelClarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUserIconClar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldUserClar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparatorUserClar, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabelPasswordClar)
                .addGap(18, 18, 18)
                .addGroup(jPanelClarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPasswordIconClar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordFieldClar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparatorPasswordClar, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(jLabelLoginClar)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        jPanelRight.add(jPanelClar, "card2");

        getContentPane().add(jPanelRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 400, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param evt Tanca el client Login Fosc d'escriptori
     */
    private void jLabelCloseFoscMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseFoscMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelCloseFoscMouseClicked

    /**
     * -- Versió Fosca --
     * @param evt Botó per Iniciar Sessió al client d'escriptori
     * Primer fa la connexió amb el servidor creat mitjançant un try/catch
     * Li fem la crida com requereix el servidor per fer Login i li pasem els valors agafats pel camp de text i contrasenya creant una conexió
     * Si els paràmetres son incorrectes ens surt un avís i tanca aquesta conexió creada
     * Si els paràmetres son correctes, segons el rol del usuari obrira el JFrame referent
     */
    private void jLabelLoginFoscMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLoginFoscMouseClicked
        Socket sc;
        try {
            sc = new Socket("127.0.0.1", 5000);
            DataInputStream in = new DataInputStream(sc.getInputStream());
            DataOutputStream out = new DataOutputStream(sc.getOutputStream());

            //Llegir la resposta del servidor al establir la connexió
            String resposta_svr = in.readUTF();

            //Enviem resposta al servidor amb el usuari i la contrasenya
            out.writeUTF("LOGIN," + jTextFieldUserFosc.getText().toString() + "," + jPasswordFieldFosc.getText().toString() + ",0");
            System.out.println("LOGIN," + jTextFieldUserFosc.getText().toString() + "," + jPasswordFieldFosc.getText().toString() + ",0");

            int resposta_svr_id = in.readInt();
            System.out.println("resposta servidor: " + resposta_svr);

            if (resposta_svr_id != 0) {

                int rol = in.readInt();

                if (rol == 1) {
                    //Obre finestra administrador
                    JOptionPane.showMessageDialog(this, "Benvingut/a " + jTextFieldUserFosc.getText().toString());
                    DesktopAdmin window = new DesktopAdmin();
                    window.jLabelUserConnected.setText(jTextFieldUserFosc.getText().toString() + " - #" + resposta_svr_id + " - # rol: " + rol);

                    //Envio el id de la connexió validada a la finestra
                    window.setId(resposta_svr_id);
                    window.setUsuari(jTextFieldUserFosc.getText().toString());
                    window.setPwd(jPasswordFieldFosc.getText().toString());
                    window.setRol(rol);

                    window.setVisible(true);
                    this.dispose();
                } else if (rol == 2) {
                    //Obre finestra tecnic
                    JOptionPane.showMessageDialog(this, "Benvingut/a " + jTextFieldUserFosc.getText().toString());
                    DesktopTecnic window = new DesktopTecnic();
                    window.jLabelUserConnected.setText(jTextFieldUserFosc.getText().toString() + " - #" + resposta_svr_id + " - # rol: " + rol);

                    //Envio el id de la connexió validada a la finestra
                    window.setId(resposta_svr_id);
                    window.setUsuari(jTextFieldUserFosc.getText().toString());
                    window.setPwd(jPasswordFieldFosc.getText().toString());
                    window.setRol(rol);

                    window.setVisible(true);
                    this.dispose();
                } else {
                    //Misstge que es usuari i no te credencials
                    JOptionPane.showMessageDialog(this, "Aquest usuari no te credencials per aquest aplicatiu. Inicia sessió amb el client mòbil.");
                    logout(jTextFieldUserFosc.getText().toString(), jPasswordFieldFosc.getText().toString(), resposta_svr_id);
                }

            } else {
                JOptionPane.showMessageDialog(this, "Error de usuari o contrasenya");
            }

        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "No es pot establir connexió amb el servidor");
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabelLoginFoscMouseClicked

    /**
     * @param evt Tanca el client Login Clar d'escriptori
     */
    private void jLabelCloseClarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseClarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelCloseClarMouseClicked

    /**
     * -- Versió Clara --
     * @param evt Botó per Iniciar Sessió al client d'escriptori
     * Primer fa la connexió amb el servidor creat mitjançant un try/catch
     * Li fem la crida com requereix el servidor per fer Login i li pasem els valors agafats pel camp de text i contrasenya creant una conexió
     * Si els paràmetres son incorrectes ens surt un avís i tanca aquesta conexió creada
     * Si els paràmetres son correctes, segons el rol del usuari obrira el JFrame referent
     */
    private void jLabelLoginClarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLoginClarMouseClicked
        Socket sc;
        try {
            sc = new Socket("127.0.0.1", 5000);
            DataInputStream in = new DataInputStream(sc.getInputStream());
            DataOutputStream out = new DataOutputStream(sc.getOutputStream());

            //Llegir la resposta del servidor al establir la connexió
            String resposta_svr = in.readUTF();

            //Enviem resposta al servidor amb el usuari i la contrasenya
            out.writeUTF("LOGIN," + jTextFieldUserClar.getText().toString() + "," + jPasswordFieldClar.getText().toString() + ",0");
            System.out.println("LOGIN," + jTextFieldUserClar.getText().toString() + "," + jPasswordFieldClar.getText().toString() + ",0");

            int resposta_svr_id = in.readInt();
            System.out.println("resposta servidor: " + resposta_svr);

            if (resposta_svr_id != 0) {

                int rol = in.readInt();

                if (rol == 1) {
                    //Obre finestra administrador
                    JOptionPane.showMessageDialog(this, "Benvingut/a " + jTextFieldUserClar.getText().toString());
                    //Aqui s'haura de posar que obri l'aplicatiu en mode clar
                    DesktopAdmin window = new DesktopAdmin();
                    window.jLabelUserConnected.setText(jTextFieldUserClar.getText().toString() + " - #" + resposta_svr_id + " - # rol: " + rol);

                    //Envio el id de la connexió validada a la finestra
                    window.setId(resposta_svr_id);
                    window.setUsuari(jTextFieldUserClar.getText().toString());
                    window.setPwd(jPasswordFieldClar.getText().toString());
                    window.setRol(rol);

                    window.setVisible(true);
                    this.dispose();
                } else if (rol == 2) {
                    //Obre finestra tecnic
                    JOptionPane.showMessageDialog(this, "Benvingut/a " + jTextFieldUserClar.getText().toString());
                    DesktopTecnic window = new DesktopTecnic();
                    window.jLabelUserConnected.setText(jTextFieldUserClar.getText().toString() + " - #" + resposta_svr_id + " - # rol: " + rol);

                    //Envio el id de la connexió validada a la finestra
                    window.setId(resposta_svr_id);
                    window.setUsuari(jTextFieldUserClar.getText().toString());
                    window.setPwd(jPasswordFieldClar.getText().toString());
                    window.setRol(rol);

                    window.setVisible(true);
                    this.dispose();
                } else {
                    //Misstge que es usuari i no te credencials
                    JOptionPane.showMessageDialog(this, "Aquest usuari no te credencials per aquest aplicatiu. Inicia sessió amb el client mòbil.");
                    logout(jTextFieldUserClar.getText().toString(), jPasswordFieldClar.getText().toString(), resposta_svr_id);
                }

            } else {
                JOptionPane.showMessageDialog(this, "Error de usuari o contrasenya");
            }

        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "No es pot establir connexió amb el servidor");
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabelLoginClarMouseClicked

    /**
     * @param evt Activa el mode Clar de la pantalla de Login
     */
    private void jLabelClarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelClarMouseClicked
        jPanelClar.setVisible(true);
        jPanelFosc.setVisible(false);
        jTextFieldUserFosc.setText(null);
        jPasswordFieldFosc.setText(null);
    }//GEN-LAST:event_jLabelClarMouseClicked

    /**
     * @param evt Activa el mode Fosc de la pantalla de Login
     */
    private void jLabelFoscMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelFoscMouseClicked
        jPanelFosc.setVisible(true);
        jPanelClar.setVisible(false);
        jTextFieldUserClar.setText(null);
        jPasswordFieldClar.setText(null);
    }//GEN-LAST:event_jLabelFoscMouseClicked

    /**
     * @param usuari
     * @param pwd
     * @param id 
     * Envia la petició de logout al servidor
     */
    private void logout(String usuari, String pwd, int id) {

        Socket sc;
        try {
            sc = new Socket("127.0.0.1", 5000);
            DataInputStream in = new DataInputStream(sc.getInputStream());
            DataOutputStream out = new DataOutputStream(sc.getOutputStream());

            // Llegir la resposta del servidor al establir la connexió
            String resposta_svr = in.readUTF();
            //Enviem resposta al servidor amb el usuari i la contrasenya
            out.writeUTF("LOGIN," + usuari + "," + pwd + "," + id);
            //Executo la consulta de la crida per sortir
            out.writeUTF("USER_EXIT");
            System.out.println("Valor getId: " + id);

        } catch (IOException ex) {
            Logger.getLogger(DesktopPlantillaFosc.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelClar;
    private javax.swing.JLabel jLabelCloseClar;
    private javax.swing.JLabel jLabelCloseFosc;
    private javax.swing.JLabel jLabelFosc;
    private javax.swing.JLabel jLabelLoginClar;
    private javax.swing.JLabel jLabelLoginFosc;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelPasswordClar;
    private javax.swing.JLabel jLabelPasswordFosc;
    private javax.swing.JLabel jLabelPasswordIconClar;
    private javax.swing.JLabel jLabelPasswordIconFosc;
    private javax.swing.JLabel jLabelUserClar;
    private javax.swing.JLabel jLabelUserFosc;
    private javax.swing.JLabel jLabelUserIconClar;
    private javax.swing.JLabel jLabelUserIconFosc;
    private javax.swing.JPanel jPanelClar;
    private javax.swing.JPanel jPanelFosc;
    private javax.swing.JPanel jPanelLeft;
    private javax.swing.JPanel jPanelRight;
    private javax.swing.JPasswordField jPasswordFieldClar;
    private javax.swing.JPasswordField jPasswordFieldFosc;
    private javax.swing.JSeparator jSeparatorPasswordClar;
    private javax.swing.JSeparator jSeparatorPasswordFosc;
    private javax.swing.JSeparator jSeparatorUserClar;
    private javax.swing.JSeparator jSeparatorUserFosc;
    private javax.swing.JTextField jTextFieldUserClar;
    private javax.swing.JTextField jTextFieldUserFosc;
    private javax.swing.JLabel loginTextIniciarFosc;
    private javax.swing.JLabel loginTextIniciarSesionClar;
    // End of variables declaration//GEN-END:variables
}
